# Generated by Django 5.0.3 on 2024-03-17 16:59

import billing.json_mappers
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('house_reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseReservationPromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='Промокод')),
                ('enabled', models.BooleanField(default=True)),
                ('discount_type', models.CharField(choices=[('FIXED', 'Скидка на фиксированную сумму'), ('PERCENTAGE', 'Скидка на процент от чека')], max_length=15)),
                ('discount_value', models.IntegerField()),
                ('max_use_times', models.IntegerField(default=1)),
                ('minimal_bill_value', models.IntegerField(default=0)),
                ('issuance_datetime', models.DateTimeField(blank=True, default=None, null=True)),
                ('expiration_datetime', models.DateTimeField(blank=True, default=None, null=True)),
                ('client', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='HouseReservationBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0, verbose_name='Итоговая стоимость')),
                ('chronological_positions', models.JSONField(blank=True, decoder=billing.json_mappers.ChronologicalPositionsDecoder, default=dict, encoder=billing.json_mappers.ChronologicalPositionsEncoder, verbose_name='Хронологически упорядоченные позиции')),
                ('non_chronological_positions', models.JSONField(blank=True, decoder=billing.json_mappers.NonChronologicalPositionsDecoder, default=dict, encoder=billing.json_mappers.NonChronologicalPositionsEncoder, verbose_name='Хронологически неупорядоченные позиции')),
                ('paid', models.BooleanField(default=False)),
                ('reservation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='house_reservations.housereservation', verbose_name='Счет на оплату бронирования домика')),
                ('promo_code', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='billing.housereservationpromocode', verbose_name='Промокод')),
            ],
            options={
                'verbose_name': 'Счет на оплату бронирования домика',
                'verbose_name_plural': 'Счета на оплату бронирования домиков',
            },
        ),
    ]
