# Generated by Django 5.0.3 on 2024-03-17 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housereservationbill',
            name='total',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(100)], verbose_name='Итоговая стоимость'),
        ),
    ]
