# Generated by Django 5.0.3 on 2024-03-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_housereservationbill_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housereservationbill',
            name='extra_services',
        ),
        migrations.RemoveField(
            model_name='housereservationbill',
            name='nights',
        ),
        migrations.AddField(
            model_name='housereservationbill',
            name='chronological_positions',
            field=models.JSONField(default=dict, verbose_name='Хронологически упорядоченные позиции'),
        ),
        migrations.AddField(
            model_name='housereservationbill',
            name='non_chronological_positions',
            field=models.JSONField(default=dict, verbose_name='Хронологически неупорядоченные позиции'),
        ),
    ]
