# Generated by Django 5.0.3 on 2024-03-17 14:30

import billing.json_mappers
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_remove_housereservationbill_extra_services_and_more'),
        ('house_reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='housereservationpromocode',
            name='minimal_bill_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='housereservationbill',
            name='chronological_positions',
            field=models.JSONField(blank=True, decoder=billing.json_mappers.ChronologicalPositionsDecoder, default=dict, encoder=billing.json_mappers.ChronologicalPositionsEncoder, verbose_name='Хронологически упорядоченные позиции'),
        ),
        migrations.AlterField(
            model_name='housereservationbill',
            name='non_chronological_positions',
            field=models.JSONField(blank=True, decoder=billing.json_mappers.ChronologicalPositionsDecoder, default=dict, encoder=billing.json_mappers.ChronologicalPositionsEncoder, verbose_name='Хронологически неупорядоченные позиции'),
        ),
        migrations.AlterField(
            model_name='housereservationbill',
            name='reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='house_reservations.housereservation', verbose_name='Счет на оплату бронирования домика'),
        ),
    ]
