FIXED_VALUE_DISCOUNT = "FIXED"
PERCENTAGE_DISCOUNT = "PERCENTAGE"

NIGHT_POSITION = 'night'
EARLY_CHECK_IN_POSITION = 'early_check_in'
LATE_CHECK_OUT_POSITION = 'late_check_out'
PROMO_CODE_POSITION = 'promo_code'
EXTRA_PERSONS_POSITION = 'extra_persons'
