version: '2'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '${BACKEND_PORT}:8000'
    volumes:
      - .:/app
    env_file:
      - ../.env
