version: '2'

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '${BACKEND_PORT}:8000'
    volumes:
      - .:/app/backend
    env_file:
      - ../.env
    networks:
      - nikola-docker-network

networks:
  nikola-docker-network:
    external: true
