version: '2'

services:
  backend:
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '${BACKEND_PORT}:8000'
    volumes:
      - .:/app/backend
    depends_on:
      - db
      - redis
    links:
      - db:db
      - redis:redis
    env_file:
      - ../.env

  db:
    image: postgres
    env_file: ../.env

  redis:
    image: library/redis
    restart: unless-stopped
    ports:
      - '${REDIS_PORT}:6379'
