# Generated by Django 4.2.6 on 2023-10-16 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название домика')),
                ('description', models.TextField(verbose_name='Описание домика')),
                ('base_price', models.IntegerField(verbose_name='Базовая цена')),
                ('holidays_multiplier', models.FloatField(default=1, verbose_name='Множитель в выходные и праздники')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Домик',
                'verbose_name_plural': 'Домики',
            },
        ),
        migrations.CreateModel(
            name='HousePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture',
                 models.ImageField(storage='django_hashedfilenamestorage.storage.HashedFilenameFileSystemStorage',
                                   upload_to='houses/pictures')),
                ('house',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pictures',
                                   to='houses.house')),
            ],
            options={
                'verbose_name': 'Изображение домика',
                'verbose_name_plural': 'Изображения домиков',
            },
        ),
    ]
