# Generated by Django 5.0.3 on 2024-03-17 16:59

import django.core.validators
import django.db.models.deletion
import houses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, unique=True, verbose_name='Название')),
                ('icon', models.ImageField(upload_to=houses.models.generate_house_feature_picture_filename, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Фича домика',
                'verbose_name_plural': 'Фичи домиков',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название домика')),
                ('description', models.TextField(verbose_name='Описание домика')),
                ('base_price', models.IntegerField(default=10000, validators=[django.core.validators.MinValueValidator(5000, message='Базовая цена домика должна быть не меньше, чем 5000')], verbose_name='Базовая цена')),
                ('holidays_multiplier', models.FloatField(default=2, validators=[django.core.validators.MinValueValidator(1, message='Множитель в выходные дни должен быть не меньше, чем 1')], verbose_name='Множитель в выходные и праздники')),
                ('base_persons_amount', models.IntegerField(default=2, verbose_name='Базовое количество человек для проживания в домике')),
                ('max_persons_amount', models.IntegerField(default=3, verbose_name='Максимальное количество человек для проживания в домике')),
                ('price_per_extra_person', models.IntegerField(default=2000, verbose_name='Цена за дополнительного человека')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания домика')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения домика')),
                ('features', models.ManyToManyField(related_name='houses', to='houses.housefeature', verbose_name='Плюшки')),
            ],
            options={
                'verbose_name': 'Домик',
                'verbose_name_plural': 'Домики',
            },
        ),
        migrations.CreateModel(
            name='HousePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to=houses.models.generate_house_picture_filename, verbose_name='Путь до файла с изображением')),
                ('house', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pictures', to='houses.house', verbose_name='Домик')),
            ],
            options={
                'verbose_name': 'Изображение домика',
                'verbose_name_plural': 'Изображения домиков',
            },
        ),
    ]
