# Generated by Django 4.2.6 on 2023-10-18 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_first_name_alter_client_last_name'),
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='closed',
        ),
        migrations.AlterField(
            model_name='housereservation',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='clients.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='housereservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания бронирования'),
        ),
        migrations.AlterField(
            model_name='housereservation',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='houses.house', verbose_name='Домик'),
        ),
        migrations.AlterField(
            model_name='housereservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения бронирования'),
        ),
    ]
