# Generated by Django 5.0.3 on 2024-06-09 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housefeature',
            old_name='icon',
            new_name='picture',
        ),
    ]
