# Generated by Django 4.2.6 on 2023-10-16 21:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_alter_house_base_price_alter_house_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='base_price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1000, message='Базовая цена домика должна быть не меньше, чем 1000')], verbose_name='Базовая цена'),
        ),
        migrations.AlterField(
            model_name='house',
            name='holidays_multiplier',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Множитель в выходные дни должен быть не меньше, чем 1')], verbose_name='Множитель в выходные и праздники'),
        ),
    ]
