# Generated by Django 4.2.6 on 2023-10-19 13:59

from django.db import migrations, models
import houses.models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_remove_house_closed_alter_housereservation_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, unique=True, verbose_name='Название')),
                ('icon', models.ImageField(upload_to=houses.models.generate_house_feature_icon_filename, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Фича домика',
                'verbose_name_plural': 'Фичи домиков',
            },
        ),
        migrations.AddField(
            model_name='house',
            name='features',
            field=models.ManyToManyField(related_name='houses', to='houses.housefeature', verbose_name='Плюшки'),
        ),
    ]
