# Generated by Django 4.2.6 on 2023-10-23 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_rename_max_occupancy_house_max_persons_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housereservation',
            name='extra_persons_amount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='В бронировании нельзя указывать отрицательное количество человек')], verbose_name='Дополнительное количество человек для проживания в домике'),
        ),
    ]
