# Generated by Django 5.0.3 on 2024-05-30 18:50

import core.generators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_reservations', '0002_housereservation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housereservation',
            name='slug',
            field=models.CharField(default=core.generators.slug_generator, max_length=64, verbose_name='Строковый идентификатор'),
        ),
    ]
