# Generated by Django 5.0.3 on 2024-08-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_reservations', '0003_alter_housereservation_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='housereservation',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Подтверждено менеджером?'),
        ),
    ]
