# Generated by Django 5.0.3 on 2024-09-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_reservations', '0004_housereservation_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housereservation',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=511, verbose_name='Комментарий'),
        ),
    ]
