# Generated by Django 5.0.3 on 2024-06-29 12:48

import additional_services.filepath_generators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название услуги')),
                ('description', models.TextField(verbose_name='Описание услуги')),
                ('telegram_contact_link', models.CharField(max_length=127, verbose_name='Ссылка на телеграм для бронирования')),
                ('price_string', models.CharField(max_length=15, verbose_name='Стоимость услуги')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания услуги')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='AdditionalServicePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to=additional_services.filepath_generators.generate_additional_service_picture_filename, verbose_name='Путь до файла с изображением')),
                ('additional_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pictures', to='additional_services.additionalservice', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Изображение услуги',
                'verbose_name_plural': 'Изображения услуг',
            },
        ),
    ]
