# Generated by Django 4.2.6 on 2023-10-16 21:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email адрес')),
                ('first_name', models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(message='Имя и фамилия должны состоять из только из цифр, "                                        "строчных и заглавных букв русского "                                        "и английского алфавитов, пробелов, а также из символов ",.\'-")', regex="^[0-9a-zA-Zа-яА-Я ,.'-]+$")], verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(message='Имя и фамилия должны состоять из только из цифр, "                                        "строчных и заглавных букв русского "                                        "и английского алфавитов, пробелов, а также из символов ",.\'-")', regex="^[0-9a-zA-Zа-яА-Я ,.'-]+$")], verbose_name='Фамилия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
